# config.ini
[General]
# debug = true
# log_level = "INFO"

#####################################################
###                    CLIENT                     ###
#####################################################

[scan]
range = "192.168.20.0/24"
port = 42532
timeout_connect = 800
timeout_request = 4
max_concurrent = 100
old_host_threshold = 48

[security]
allowed_hosts = ["NEWUSER", "LaptopCasa", "192.168.1.45", "TrabajoPC"]

#####################################################
###                    BACKEND                    ###
#####################################################

[backend]
backend_port = 42532
temp_directory = "downloads"

[meet]
hostname = "s7lverpc"
passphrase = "supersecret123"