last_seen = 

[s7lverpc]
hostname   = s7lverpc
passphrase = supersecret123
address    = 192.168.0.19
ip         = 192.168.0.19
last_seen  = 1769180962

[NEWUSER]
hostname   = NEWUSER
passphrase = supersecret123
address    = 192.168.0.74
ip         = 192.168.0.74
last_seen  = 1769180962
